### PR TITLE
Fix Real-Time Comment Updates Issue

### LINKED ISSUE #289: Comment without page reload
**Describe the bug**
After commenting under a blog post, the page reloads and I am sent to the top of the page.

### PR DESCRIPTION
**Pull request by freedompraise**
**Description:**

This pull request addresses the issue of real-time comment updates and the occurrence of page duplication after creating a comment. I've implemented a solution to provide real-time comment updates without relying on JavaScript. By utilizing Django htmx, comments are updated in real-time for users without requiring page reloads.

While real-time comment updates have been successfully implemented, the issue of page duplication remains a challenge.

**Changes Made:**
- Implemented Django htmx to provide real-time comment updates without JavaScript.

**Testing:**

I've thoroughly tested these changes:

- Successfully submitted new comments.
- Verified that real-time updates are reflected in the comments section.

Related Issues:

Fixes #289 : Real-time comment updates.

### CODE REVIEW

**Comment by jsolly** [comment]
Hi @freedompraise I added a commit that solves the duplicate page issue.

The only remaining issue is that the comment form is not cleared on submission. Can you see if you can figure out a solution for that?


https://github.com/jsolly/awesome-django-blog/assets/9572232/03f95dce-7ca9-43ca-bb8b-dc9f922f7936

**Comment by jsolly** [comment]
@freedompraise have a look at my recent commits and try it out yourself. If it looks good to you, let me know and we will merge.

**Comment by freedompraise** [comment]
> @freedompraise have a look at my recent commits and try it out yourself. If it looks good to you, let me know and we will merge. I believe I have resolved all of the issues.

Okay

**Comment by freedompraise** [comment]
> > @freedompraise have a look at my recent commits and try it out yourself. If it looks good to you, let me know and we will merge. I believe I have resolved all of the issues.
> 
> Okay



> > @freedompraise have a look at my recent commits and try it out yourself. If it looks good to you, let me know and we will merge. I believe I have resolved all of the issues.
> 
> Okay

I think it's cool. 
You can merge

**Pull request merged**
